### ISSUE TITLE
Settings link in plugins.php is invalid

### ISSUE THREAD

**Issue by pixolin** [BinaryMoon/wp-toolbelt#44] opened 2019-09-21 11:45 UTC
Settings link in `plugins.php` points to https://wp.local/wp-admin/admin.php?page=toolbelt-settings, which no longer exists after changes in version 2.0.

**Comment by pixolin** [comment] 2019-09-21 12:05
Sorry for the various pull requests; I had some difficulties switching off automatic code formatting in my editor.

**Comment by BinaryMoon** [comment] 2019-09-21 12:29
I knew I was going to miss something. Thanks for the pull request! I'll get this into a 2.0.1 update

**Comment by ndegruchy** [comment] 2019-11-24 01:43
This link is present, again. Regression?

**Comment by BinaryMoon** [comment] 2019-11-24 19:43
It seems to be working for me. The link should be there, the problem was that it was pointing to a page that didn't exist.

Or is that what is wrong here too? The link is there but the page doesn't exist?

**Comment by pixolin** [comment] 2019-11-25 09:35
On `wp-admin/plugins.php` the plugin shows three links: 

* Modules (`wp-admin/admin.php?page=toolbelt-modules`) ☑️
* Settings (`wp-admin/admin.php?page=toolbelt-settings`) 🚫
* Deactivate (`wp-admin/plugins.php?action=deactivate&plugin=wp-toolbelt…`)  ☑️

The Settings-Link is broken and results in a core message 

> you don't have permission to access this page

**Comment by ndegruchy** [comment] 2019-11-25 13:41
> On `wp-admin/plugins.php` the plugin shows three links:
> 
>     * Modules (`wp-admin/admin.php?page=toolbelt-modules`) ballot_box_with_check
> 
>     * Settings (`wp-admin/admin.php?page=toolbelt-settings`) no_entry_sign
> 
>     * Deactivate (`wp-admin/plugins.php?action=deactivate&plugin=wp-toolbelt…`)  ballot_box_with_check
> 
> 
> The Settings-Link is broken and results in a core message
> 
> > you don't have permission to access this page

This is exactly right. When you click on the settings link, it goes to the error page, regardless of user level. I *just* installed 2.4.0 and the same issue occurs there.

**Comment by BinaryMoon** [comment] 2019-11-25 19:30
Ok - it works for me.

What I guess is happening is that you don't have all the modules active and so it's showing the link but you don't have any modules that use the settings page. I thought I checked for this but something may have gone wrong so I'll see if I can work it out! :)

**Comment by BinaryMoon** [comment] 2019-11-25 19:44
ah ha - found it. Will be fixed in the next update. Thanks for pointing it out!

**Closed** 2019-12-08 09:15 UTC
