### ISSUE TITLE
Logged in and Logged out users are getting different scripts and stylesheets with Toolbelt enabled.

### ISSUE THREAD

**Issue by greggh** [BinaryMoon/wp-toolbelt#53] opened 2019-09-26 23:43 UTC
When WP Toolbelt is enabled on our site logged out users are getting pages that look very broken. This is due to multiple scripts and stylesheets not getting loaded and possibly other errors. Everything goes back to normal and works great when I disable this plugin.

I absolutely love this plugin and really don't want to leave it disabled. So I am hoping this can be figured out.

Again the important bit for me, logged in users are working fine. This is only happening to logged out users. I would be happy to allow you access to my site to debug if needed. It is currently in development and not open to the public yet, so I prefer not to post it, or screenshots of it.

**Comment by greggh** [comment] 2019-09-26 23:46
I have entries in functions.php in my child theme to alter Toolbelt, I can't see any of them being the problem, but here they are:

`
// set which post types social share buttons appear on
function my_social_sharing_post_types() {
	return array( 'post', 'page', 'company', 'job_listing', 'product', 'forum', 'topic', 'reply', 'discussion' );
}
add_filter( 'toolbelt_social_sharing_post_types', 'my_social_sharing_post_types' );

// exclude some pages from social sharing buttons
function my_display_social_sharing() {
	// Hide for post id 4.
	$the_id = (int) get_the_ID();
	$page_ids = array(2647, 2692, 2852, 2942, 2952, 3007, 16992, 17042, 17897, 21532, 21537, 23132, 34207, 49507, 54037, 55207, 56402);
	if ( in_array( $the_id, $page_ids) ) {
		return false;
	}
	// Show for all other posts.
	return true;
}
add_filter( 'toolbelt_display_social_sharing', 'my_display_social_sharing' );

// Change display text for cookie banner
function my_cookie_banner_message( $message ) {
	return 'Multileveling.com uses cookies. You can view our Cookies Poilicy <a href="https://multileveling.com/cookies-policy/">here</a>.';
}
add_filter( 'toolbelt_cookie_message', 'my_cookie_banner_message' );

function my_cookie_button_text( $text ) {
	$text['accept'] = 'Yes please';
	$text['decline'] = 'Nope';
	$text['close'] = 'Accept';
	return $text;
}
add_filter( 'toolbelt_cookie_button_text', 'my_cookie_button_text' );
`

**Comment by greggh** [comment] 2019-09-27 02:12
I realized it was the Header Cleanup module causing the problem. I would love to use it, but it is defiintely acting weird on my setup.

**Comment by BinaryMoon** [comment] 2019-09-27 10:43
Hi Gregg - thanks for the bug report. I'm currently on holiday but will look into this next week when I'm back.

**Comment by BinaryMoon** [comment] 2019-09-30 16:34
Hi Gregg - I'm home now :)

If you can't share it publicly would you mind emailing me the info so I can take a look at your site and see the problem myself? My email address is binarymoon at gmail dot com - thanks

**Comment by greggh** [comment] 2019-09-30 16:43
Email incoming.

**Comment by BinaryMoon** [comment] 2019-09-30 21:02
Well I've had a look and I think I see what you mean. It's a very strange thing. I can't see any reason why it would be happening at the moment, but I'll take another look tomorrow and see if I can get to the bottom of it.

**Comment by greggh** [comment] 2019-09-30 22:09
I appreciate that. I loved the feature, so I would really like to turn it back on.

**Comment by BinaryMoon** [comment] 2019-10-01 10:02
It looks like some styles from buddyboss aren't being loaded but I have no idea why. As long as the scripts and styles are loaded "properly" then they should work ok. The plugin doesn't (intentionally) do anything to stop styles from loading.

Since BuddyBoss appears to be premium/ closed source I am not sure I can help with this. Could you ask them for help? If they can work out where the problem is then I can probably tweak the module to work (or they can tweak their plugin to not conflict).

**Comment by greggh** [comment] 2019-10-01 14:05
I will ask them for help and report back if/when I get anything.

**Comment by BinaryMoon** [comment] 2019-10-14 08:36
Hi Gregg - did you ever find out what the problem was here?

**Comment by greggh** [comment] 2019-10-14 14:20
Nope. They said support for this would be on your end. And I don't actually buy that, so I just left it alone.

**Comment by BinaryMoon** [comment] 2019-10-14 18:25
That's a shame. It's always awkward when there's two developers each blaming the other.

The conflict is definitely with their plugin since their css isn't loading. It may be a problem in my code, but since I don't know their code I can't debug it myself to find out where the problem is. The Optimization functionality doesn't do anything with the default style enqueuing code so I'm not sure what would be missing to stop it from working.

**Comment by BinaryMoon** [comment] 2019-10-14 18:26
I'm gonna close this since I'm not sure how to proceed, but let me know if you ever work out what the problem is and I will be happy to tweak the plugin to try and stop it from happening.

**Closed by BinaryMoon** 2019-10-14 18:26 UTC

**Comment by greggh** [comment] 2019-10-15 00:42
I'll definitely tell you if we ever figure it out.
