### ISSUE TITLE
Widget Display 'exclusion' doesn't seem to be working

### ISSUE THREAD

**Issue by bishless** [BinaryMoon/wp-toolbelt#63] opened 2019-11-06 23:21 UTC
I have a widget I want to display in the footer everywhere except for one specific page - say, page id: 414. I've been looking over the [documentation](https://github.com/BinaryMoon/wp-toolbelt/wiki/Widget-Display) for this feature...

If I add this rule to the widget: `single:-414`

That widget doesn't display anywhere on the site. How do I need to modify my rule(s)?

**Comment by BinaryMoon** [comment] 2019-11-07 12:40
Hi there - thanks for the message.

I've been testing this and I see what you mean. It doesn't seem to work as I had hoped. Not sure how to fix this at the moment but I'll see what I can do as this is a use case I thought would work.

**Comment by BinaryMoon** [comment] 2019-11-26 23:01
It's taken a while but I've rewritten the code and it seems to work now. The change will be in the next update. The rule will now need to be: `!single:414`

The _not_ will apply to all ids in the rule. I still need to update the docs to reflect the changes but this should do the job (and make the rest of the module more powerful too)

**Comment by BinaryMoon** [comment] 2019-12-04 21:19
@bishless Hi - have you had a chance to try this? Would be great to find out if it helped.

**Comment by bishless** [comment] 2019-12-04 22:17
I'm sorry for the delay @BinaryMoon 
I got a chance to try it out, but it doesn't seem to do what I'd expect. Does `single` apply to pages?

With the following rule: `home; archive; !single:414; postType:page;` the widget does not display on 'archive/index' views... but it displays everywhere else - including page id 414.

**Comment by BinaryMoon** [comment] 2019-12-05 09:17
Single does apply to pages. I think the problem (now) might be in the way the rules are read when there's more than one. From my tests the single rules work well but it gets confused when there's multiple rules.

**Comment by bishless** [comment] 2019-12-05 16:12
Hmm... when I use `!single: 414` the widget doesn't display on the page w/ 414 as the id, however, it also does not display on any other pages.

**Comment by BinaryMoon** [comment] 2019-12-06 09:35
I can't work out if that's intentional or not! :)

Since you raised this I've been building a test suite so that I can try to confirm this thing works as intended. It's a lot more complicated than I first thought. Getting use cases like you showed me above gets added to my test suite so I can try to make sure it works as intended.

I did find after I added your rule to my test suite that it was working as you just described but I thought that was because of changes I had made to the code since. I didn't realise it had always been like that. Hopefully the changes I am making now will improve things further.

**Comment by bishless** [comment] 2019-12-18 20:57
`single` and `!single` both seem to be working well now.

However, I'm noticing that `archive` doesn't seem to work for me. When I add `archive` to the ruleset, the widget does not show up where I'd expect it - the main blog posts page, nor a category archive.

**Comment by BinaryMoon** [comment] 2019-12-19 08:20
That's great that single is working now. I've just tested archive and it seems to be working as I expect, but perhaps I expect something different to you.

The archive rule should only work where is_archive works, so I don't think that works on the homepage. It should work on category/ tag archives though. Do you have a ruleset that you're testing that I can try? I'd like to make sure there's not something else conflicting.

**Closed** 2020-08-20 21:19 UTC
